trigger:
  - main

pool: 'GlobalPass DevOps'

steps:
  - checkout: self
  
  - task: NodeTool@0
    inputs:
      versionSpec: '16.x'
    displayName: 'Install Node.js'

  - script: |
      npm install --global yarn
      yarn install
    displayName: Install Yarn

  - script: |
      yarn build
    displayName: Build

  - task: AzureStaticWebApp@0
    displayName: Deploy
    inputs:
      app_location: '/build'
      output_location: ''
      skip_app_build: true
      azure_static_web_apps_api_token: $(deployment_token)
