/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  apiIntegrationGuideSidebar: [
    {
      type: "autogenerated",
      dirName: "api-integration-guide",
    },
  ],
  // androidSdkSidebar: [
  //   {
  //     type: 'autogenerated',
  //     dirName: 'android-sdk'
  //   }
  // ],
  androidSdkSidebar: [
    {
      type: "category",
      label: "Android",
      link: {
        type: "generated-index",
        description:
          "These are the guides on how to integrate GlobalPass to Android devices through our SDK solution. We support different platforms for Android devices.",
      },
      items: [
        "android-sdk/flutter",
        "android-sdk/native",
        "android-sdk/react-native/react-native",
      ],
      collapsible: false,
    },
  ],
  iosSdkSidebar: [
    {
      type: "category",
      label: "iOS",
      link: {
        type: "generated-index",
        description:
          "These are the guides on how to integrate GlobalPass to iOS devices through our SDK solution. We support different platforms for iOS devices.",
      },
      items: [
        "ios-sdk/flutter",
        "ios-sdk/native/native",
        "ios-sdk/react-native/react-native",
      ],
      collapsible: false,
    },
  ],
  // iosSdkSidebar: [
  //   {
  //     type: 'autogenerated',
  //     dirName: 'sdk/ios'
  //   }
  // ]
  // apiSidebar: [
  //   {
  //     type: 'autogenerated',
  //     dirName: './api-integration-guide'
  //   }
  // ]
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

module.exports = sidebars;
